---
version: "2"
linters:
  default: all
  disable:
    # it should improve to support more known patterns
    - varnamelen
    - nolintlint
    # it isn't our way
    - tagliatelle
    - depguard
    - revive
    - ireturn
