---
version: "2"
linters:
  default: all
  disable:
    - depguard
    # we don't use json with camel-case
    - tagliatelle
    - nolintlint
    # it should improve to support more known patterns
    - varnamelen
    - ireturn
    - revive
    - lll
    - funcorder
    - noinlineerr
    - gomoddirectives
    - gosec
  settings:
    wrapcheck:
      ignore-package-globs:
        - github.com/labstack/echo/v4
